In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import cv2

In [ ]:
img = cv2.imread(data_file_name)

In [11]:
a = np.arange(12).reshape((2, 2, 3))

In [20]:
a[1, 1]

array([ 9, 10, 11])

In [19]:
a.reshape(4, 3)[3]

array([ 9, 10, 11])

In [49]:
def norm(x_i, x_j):
    return np.sum((x_i-x_j)**2)

def QUBO_matr(img):
    """
    Find QUBO matrix  for omage recognition
    img - RGB of image pixels 
    """
    h, v, c = img.shape
    N = h*v
    x = img.reshape((N, c))/255
    qubo = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
                qubo[i, i] -= norm(x[i], x[j])
                qubo[i, j] = norm(x[i], x[j])
    return qubo

In [35]:
img = np.array([[[0, 255], [0, 255]]]).reshape((2, 2, -1))

In [50]:
Q = QUBO_matr(img)

In [55]:
x = np.array([0, 1, 1, 1])

In [56]:
Q

array([[-2.,  1.,  0.,  1.],
       [ 1., -1.,  1.,  0.],
       [ 0.,  1., -1.,  1.],
       [ 1.,  0.,  1.,  0.]])

In [57]:
x@Q@x.T

2.0